name: C++ Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Cpp (C++ / C)
        run: |
          sudo apt-get update
          sudo apt-get install -y clang parallel

      - name: Compile C++ code
        run: bash scripts/build.sh